import type { Metadata } from "next";
import "./globals.css";
import { Roboto_Flex as roboto, Montserrat } from "next/font/google";

const robotoFont = roboto({
  subsets: ["latin"],
  weight: ["700"],
  variable:"--font-roboto",
  display: "swap",
});

const montserratFont = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoFont.variable} ${montserratFont.variable} ${montserratFont.className}`}>{children}</body>
    </html>
  );
}
